services:
  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build: ./backend
    ports:
      - "5001"
    volumes:
      - ./data:/app/data
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - app_network

  interface:
    build: ./interface
    ports:
      - "5000:5000"
    depends_on:
      - nginx
    networks:
      - app_network

networks:
  app_network:
    driver: bridge